package com.android.tweaker.model

data class Strings(
    // Drawer
    val navAdbConnection: String,
    val navTweaks: String,
    val navAdbConsole: String,
    val navLanguage: String,
    val navInfo: String,
    val navLicenses: String,
    val navRateUs: String,

    // Disclaimer
    val disclaimerTitle: String,
    val disclaimerBody: String,
    val disclaimerAccept: String,

    // ADB Connection
    val statusTitle: String,
    val statusConnected: String,
    val statusConnecting: String,
    val statusDisconnected: String,
    val guideTitle: String,
    val guideSteps: String,
    val pairHeader: String,
    val pairPortLabel: String,
    val pairCodeLabel: String,
    val pairButton: String,
    val connectHeader: String,
    val adbPortLabel: String,
    val connectButton: String,
    val disconnectButton: String,

    // Danger Warnings
    val dangerStepOneTitle: String,
    val dangerStepTwoTitle: String,
    val dangerStepTwoSubtitle: String,
    val dangerCancel: String,
    val dangerProceed: String,
    val dangerProceedCountdown: String,
    val dangerProceedReady: String,

    // Categories
    val catInfoTitle: String,
    val catInfoDesc: String,
    val catAppControlTitle: String,
    val catAppControlDesc: String,
    val catSettingsTitle: String,
    val catSettingsDesc: String,
    val catDangerTitle: String,
    val catDangerDesc: String,

    // General UI
    val runCommand: String,
    val dangerExecute: String,
    val close: String,
    val selectLanguage: String,
    val appInfoAboutTitle: String,
    val appInfoAboutBody: String
)

object AppStringsProvider {
    fun getStrings(language: AppLanguage): Strings = when (language) {
        AppLanguage.ENGLISH -> Strings(
            navAdbConnection = "Adb connection",
            navTweaks = "Tweaks",
            navAdbConsole = "ADB Console",
            navLanguage = "Language",
            navInfo = "Info",
            navLicenses = "Opensource licenses",
            navRateUs = "Rate us on the play store",
            disclaimerTitle = "Disclaimer & Terms of Use",
            disclaimerBody = "IMPORTANT DISCLAIMER OF RESPONSIBILITY:\n\n" +
                    "This application provides direct execution of Android Debug Bridge (ADB) commands and low-level system tweaks.\n\n" +
                    "1. RISK OF INSTABILITY: Modifying system properties, resolution, density, or package states can lead to unexpected behavior, app crashes, or system instability.\n\n" +
                    "2. DANGER TWEAKS: Certain commands (such as disabling System UI, wiping recovery data, or changing resolution improperly) can cause a bootloop, black screen, or loss of user data.\n\n" +
                    "3. NO LIABILITY: The author and developer of Android Tweaker assume ABSOLUTELY NO RESPONSIBILITY or liability for any data loss, device bricking, hardware damage, or warranty voiding resulting from the use of this app.\n\n" +
                    "By clicking 'I Understand & Accept', you agree that you are using this application entirely at your own risk.",
            disclaimerAccept = "I Understand & Accept All Risks",
            statusTitle = "Connection Status",
            statusConnected = "Connected (127.0.0.1:%d)",
            statusConnecting = "Connecting to ADB...",
            statusDisconnected = "Disconnected",
            guideTitle = "How to connect without PC (Android 11+)",
            guideSteps = "1. Enable 'Developer Options' on your device.\n" +
                    "2. Turn ON 'Wireless Debugging' in Developer Options.\n" +
                    "3. Tap 'Pair device with pairing code'.\n" +
                    "4. Enter the Pairing Port & 6-digit Code below to Pair.\n" +
                    "5. Then enter the main Wireless Debugging Port and click Connect!",
            pairHeader = "1. Wireless Pairing (Android 11+)",
            pairPortLabel = "Pairing Port",
            pairCodeLabel = "Pairing Code",
            pairButton = "Pair Device",
            connectHeader = "2. ADB Connection",
            adbPortLabel = "ADB Port",
            connectButton = "Connect ADB",
            disconnectButton = "Disconnect",
            dangerStepOneTitle = "Are you sure you want to run this command?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "This action is extremely high-risk. Click Proceed below once the safety timer unlocks to execute.",
            dangerCancel = "Cancel",
            dangerProceed = "Proceed",
            dangerProceedCountdown = "Proceed (%d s)",
            dangerProceedReady = "PROCEED & EXECUTE NOW",
            catInfoTitle = "Information",
            catInfoDesc = "Read-only system & device diagnostics",
            catAppControlTitle = "App Control",
            catAppControlDesc = "Package management & permission controls",
            catSettingsTitle = "Settings",
            catSettingsDesc = "UI customization & system behavior tweaks",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Advanced options - Risk of bootloop or malfunction",
            runCommand = "RUN COMMAND",
            dangerExecute = "DANGER EXECUTE",
            close = "Close",
            selectLanguage = "Select Application Language",
            appInfoAboutTitle = "About Android Tweaker",
            appInfoAboutBody = "Android Tweaker is designed to let you execute low-level ADB commands, manage bloatware, customize system animations, change DPI, and tweak OS settings directly on your device without needing a computer."
        )

        AppLanguage.ITALIAN -> Strings(
            navAdbConnection = "Connessione Adb",
            navTweaks = "Tweaks",
            navAdbConsole = "Console ADB",
            navLanguage = "Lingua",
            navInfo = "Info",
            navLicenses = "Licenze opensource",
            navRateUs = "Valutaci sul Play Store",
            disclaimerTitle = "Esonero di Responsabilità",
            disclaimerBody = "IMPORTANTE ESONERO DI RESPONSABILITÀ:\n\n" +
                    "Questa applicazione fornisce l'esecuzione diretta di comandi ADB e modifiche di sistema a basso livello.\n\n" +
                    "1. RISCHIO DI INSTABILITÀ: La modifica delle proprietà di sistema, della risoluzione o dei pacchetti può causare comportamenti inaspettati o instabilità.\n\n" +
                    "2. DANGER TWEAKS: Alcuni comandi (come disabilitare la System UI o resettare la recovery) possono causare bootloop, schermo nero o perdita di dati.\n\n" +
                    "3. NESSUNA RESPONSABILITÀ: L'autore dello sviluppatore NON si assume ALCUNA RESPONSABILITÀ per eventuali danni, perdita di dati o blocchi del dispositivo.\n\n" +
                    "Premendo 'Comprendo e accetto', accetti di utilizzare l'app a tuo esclusivo rischio.",
            disclaimerAccept = "Comprendo e Accetto Tutti i Rischi",
            statusTitle = "Stato della Connessione",
            statusConnected = "Connesso (127.0.0.1:%d)",
            statusConnecting = "Connessione ADB in corso...",
            statusDisconnected = "Disconnesso",
            guideTitle = "Come collegarsi senza PC (Android 11+)",
            guideSteps = "1. Abilita 'Opzioni Sviluppatore' nelle impostazioni.\n" +
                    "2. Attiva 'Debug Wireless' nelle Opzioni Sviluppatore.\n" +
                    "3. Tocca 'Accoppia dispositivo con codice'.\n" +
                    "4. Inserisci la porta di accoppiamento e il codice a 6 cifre.\n" +
                    "5. Inserisci la porta principale del Debug Wireless e premi Connetti!",
            pairHeader = "1. Accoppiamento Wireless (Android 11+)",
            pairPortLabel = "Porta Accoppiamento",
            pairCodeLabel = "Codice Accoppiamento",
            pairButton = "Accoppia Dispositivo",
            connectHeader = "2. Connessione ADB",
            adbPortLabel = "Porta ADB",
            connectButton = "Connetti ADB",
            disconnectButton = "Disconnetti",
            dangerStepOneTitle = "Sei sicuro di voler eseguire questo comando?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "Questa azione è ad alto rischio. Premi Procedi al termine del timer di sicurezza.",
            dangerCancel = "Annulla",
            dangerProceed = "Procedi",
            dangerProceedCountdown = "Procedi (%d s)",
            dangerProceedReady = "PROCEDI ED ESEGUI ORA",
            catInfoTitle = "Informazioni",
            catInfoDesc = "Diagnostica e comandi di sola lettura",
            catAppControlTitle = "Controllo Applicazioni",
            catAppControlDesc = "Gestione pacchetti e permessi",
            catSettingsTitle = "Impostazioni",
            catSettingsDesc = "Personalizzazione UI e comportamento",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Opzioni avanzate - Rischio bootloop o malfunzionamenti",
            runCommand = "ESEGUI COMANDO",
            dangerExecute = "ESEGUI PERICOLO",
            close = "Chiudi",
            selectLanguage = "Seleziona Lingua Applicazione",
            appInfoAboutTitle = "Informazioni su Android Tweaker",
            appInfoAboutBody = "Android Tweaker consente di eseguire comandi ADB a basso livello, gestire bloatware e personalizzare l'interfaccia direttamente dal telefono senza bisogno di un computer."
        )

        AppLanguage.GERMAN -> Strings(
            navAdbConnection = "Adb-Verbindung",
            navTweaks = "Tweaks",
            navAdbConsole = "ADB-Konsole",
            navLanguage = "Sprache",
            navInfo = "Info",
            navLicenses = "Open-Source-Lizenzen",
            navRateUs = "Bewerten Sie uns im Play Store",
            disclaimerTitle = "Haftungsausschluss",
            disclaimerBody = "WICHTIGER HAFTUNGSAUSSCHLUSS:\n\nDiese Anwendung führt ADB-Befehle direkt aus. Die Verwendung erfolgt auf eigene Gefahr. Der Autor übernimmt keine Haftung für Datenverlust oder Schäden.",
            disclaimerAccept = "Ich verstehe und akzeptiere alle Risiken",
            statusTitle = "Verbindungsstatus",
            statusConnected = "Verbunden (127.0.0.1:%d)",
            statusConnecting = "Verbindung zu ADB wird hergestellt...",
            statusDisconnected = "Getrennt",
            guideTitle = "Verbindung ohne PC (Android 11+)",
            guideSteps = "1. Entwickleroptionen aktivieren.\n2. WLAN-Debugging aktivieren.\n3. Gerät mit Kopplungscode koppeln.\n4. Code & Port eingeben und verbinden!",
            pairHeader = "1. WLAN-Kopplung",
            pairPortLabel = "Kopplungs-Port",
            pairCodeLabel = "Kopplungs-Code",
            pairButton = "Gerät koppeln",
            connectHeader = "2. ADB-Verbindung",
            adbPortLabel = "ADB-Port",
            connectButton = "ADB verbinden",
            disconnectButton = "Trennen",
            dangerStepOneTitle = "Sind Sie sicher, dass Sie diesen Befehl ausführen möchten?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "Aktion mit hohem Risiko. Nach Ablauf des Timers fortfahren.",
            dangerCancel = "Abbrechen",
            dangerProceed = "Fortfahren",
            dangerProceedCountdown = "Fortfahren (%d s)",
            dangerProceedReady = "JETZT AUSFÜHREN",
            catInfoTitle = "Informationen",
            catInfoDesc = "Schreibgeschützte Systemdiagnose",
            catAppControlTitle = "App-Steuerung",
            catAppControlDesc = "Paketverwaltung & Berechtigungen",
            catSettingsTitle = "Einstellungen",
            catSettingsDesc = "UI-Anpassung & Systemverhalten",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Erweiterte Optionen - Bootloop-Risiko",
            runCommand = "BEFEHL AUSFÜHREN",
            dangerExecute = "GEFAHR AUSFÜHREN",
            close = "Schließen",
            selectLanguage = "App-Sprache auswählen",
            appInfoAboutTitle = "Über Android Tweaker",
            appInfoAboutBody = "Führen Sie ADB-Befehle direkt auf dem Gerät aus, ohne einen PC zu benötigen."
        )

        AppLanguage.FRENCH -> Strings(
            navAdbConnection = "Connexion Adb",
            navTweaks = "Tweaks",
            navAdbConsole = "Console ADB",
            navLanguage = "Langue",
            navInfo = "Info",
            navLicenses = "Licences open source",
            navRateUs = "Évaluez-nous sur le Play Store",
            disclaimerTitle = "Clause de non-responsabilité",
            disclaimerBody = "AVERTISSEMENT IMPORTANT:\n\nCette application exécute directement des commandes ADB. L'utilisation se fait à vos propres risques.",
            disclaimerAccept = "J'accepte tous les risques",
            statusTitle = "État de la connexion",
            statusConnected = "Connecté (127.0.0.1:%d)",
            statusConnecting = "Connexion ADB...",
            statusDisconnected = "Déconnecté",
            guideTitle = "Connexion sans PC (Android 11+)",
            guideSteps = "1. Activez les Options développeur.\n2. Activez le Débogage sans fil.\n3. Associez l'appareil avec un code.\n4. Entrez le port et le code!",
            pairHeader = "1. Appairage sans fil",
            pairPortLabel = "Port d'appairage",
            pairCodeLabel = "Code d'appairage",
            pairButton = "Appairer l'appareil",
            connectHeader = "2. Connexion ADB",
            adbPortLabel = "Port ADB",
            connectButton = "Connecter ADB",
            disconnectButton = "Déconnecter",
            dangerStepOneTitle = "Voulez-vous vraiment exécuter cette commande ?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "Action à haut risque. Cliquez sur Continuer une fois le minuteur écoulé.",
            dangerCancel = "Annuler",
            dangerProceed = "Continuer",
            dangerProceedCountdown = "Continuer (%d s)",
            dangerProceedReady = "EXÉCUTER MAINTENANT",
            catInfoTitle = "Informations",
            catInfoDesc = "Diagnostics système en lecture seule",
            catAppControlTitle = "Contrôle des applications",
            catAppControlDesc = "Gestion des paquets et autorisations",
            catSettingsTitle = "Paramètres",
            catSettingsDesc = "Personnalisation UI et comportement",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Options avancées - Risque de dysfonctionnement",
            runCommand = "EXÉCUTER",
            dangerExecute = "EXÉCUTER DANGER",
            close = "Fermer",
            selectLanguage = "Choisir la langue de l'application",
            appInfoAboutTitle = "À propos d'Android Tweaker",
            appInfoAboutBody = "Exécutez des commandes ADB directement sur votre téléphone sans PC."
        )

        AppLanguage.SPANISH -> Strings(
            navAdbConnection = "Conexión Adb",
            navTweaks = "Tweaks",
            navAdbConsole = "Consola ADB",
            navLanguage = "Idioma",
            navInfo = "Info",
            navLicenses = "Licencias de código abierto",
            navRateUs = "Valóranos en Play Store",
            disclaimerTitle = "Exención de responsabilidad",
            disclaimerBody = "AVISO IMPORTANTE:\n\nEsta aplicación ejecuta comandos ADB directamente. El uso es bajo su propio riesgo. El autor no asume ninguna responsabilidad.",
            disclaimerAccept = "Entiendo y acepto todos los riesgos",
            statusTitle = "Estado de conexión",
            statusConnected = "Conectado (127.0.0.1:%d)",
            statusConnecting = "Conectando a ADB...",
            statusDisconnected = "Desconectado",
            guideTitle = "Cómo conectar sin PC (Android 11+)",
            guideSteps = "1. Activa Opciones de desarrollador.\n2. Activa Depuración inalámbrica.\n3. Empareja dispositivo con código.\n4. Introduce puerto y código!",
            pairHeader = "1. Emparejamiento inalámbrico",
            pairPortLabel = "Puerto emparejamiento",
            pairCodeLabel = "Código emparejamiento",
            pairButton = "Emparejar dispositivo",
            connectHeader = "2. Conexión ADB",
            adbPortLabel = "Puerto ADB",
            connectButton = "Conectar ADB",
            disconnectButton = "Desconectar",
            dangerStepOneTitle = "¿Estás seguro de ejecutar este comando?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "Acción de alto riesgo. Haz clic en Continuar cuando el temporizador finalice.",
            dangerCancel = "Cancelar",
            dangerProceed = "Continuar",
            dangerProceedCountdown = "Continuar (%d s)",
            dangerProceedReady = "EJECUTAR AHORA",
            catInfoTitle = "Información",
            catInfoDesc = "Diagnósticos de solo lectura",
            catAppControlTitle = "Control de Aplicaciones",
            catAppControlDesc = "Gestión de paquetes y permisos",
            catSettingsTitle = "Ajustes",
            catSettingsDesc = "Personalización de la interfaz",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Opciones avanzadas - Riesgo de fallo",
            runCommand = "EJECUTAR COMANDO",
            dangerExecute = "EJECUTAR PELIGRO",
            close = "Cerrar",
            selectLanguage = "Seleccionar idioma de la aplicación",
            appInfoAboutTitle = "Acerca de Android Tweaker",
            appInfoAboutBody = "Ejecuta comandos ADB directamente en tu dispositivo sin necesidad de ordenador."
        )

        AppLanguage.PORTUGUESE -> Strings(
            navAdbConnection = "Conexão Adb",
            navTweaks = "Tweaks",
            navAdbConsole = "Console ADB",
            navLanguage = "Idioma",
            navInfo = "Info",
            navLicenses = "Licenças de código aberto",
            navRateUs = "Avalie-nos na Play Store",
            disclaimerTitle = "Isenção de Responsabilidade",
            disclaimerBody = "AVISO IMPORTANTE:\n\nEste aplicativo executa comandos ADB diretamente. O uso é por sua conta e risco.",
            disclaimerAccept = "Entendo e aceito todos os riscos",
            statusTitle = "Status da Conexão",
            statusConnected = "Conectado (127.0.0.1:%d)",
            statusConnecting = "Conectando ao ADB...",
            statusDisconnected = "Desconectado",
            guideTitle = "Como conectar sem PC (Android 11+)",
            guideSteps = "1. Ative as Opções do Desenvolvedor.\n2. Depuração por Wi-Fi.\n3. Parear dispositivo com código.\n4. Insira a porta e o código!",
            pairHeader = "1. Pareamento Wi-Fi",
            pairPortLabel = "Porta de Pareamento",
            pairCodeLabel = "Código de Pareamento",
            pairButton = "Parear Dispositivo",
            connectHeader = "2. Conexão ADB",
            adbPortLabel = "Porta ADB",
            connectButton = "Conectar ADB",
            disconnectButton = "Desconectar",
            dangerStepOneTitle = "Tem certeza que deseja executar este comando?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "Ação de alto risco. Clique em Prosseguir quando o temporizador destravar.",
            dangerCancel = "Cancelar",
            dangerProceed = "Prosseguir",
            dangerProceedCountdown = "Prosseguir (%d s)",
            dangerProceedReady = "EXECUTAR AGORA",
            catInfoTitle = "Informações",
            catInfoDesc = "Diagnósticos do sistema",
            catAppControlTitle = "Controle de Apps",
            catAppControlDesc = "Gerenciamento de pacotes e permissões",
            catSettingsTitle = "Configurações",
            catSettingsDesc = "Personalização da interface",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Opções avançadas - Risco de bootloop",
            runCommand = "EXECUTAR COMANDO",
            dangerExecute = "EXECUTAR PERIGO",
            close = "Fechar",
            selectLanguage = "Selecionar idioma do aplicativo",
            appInfoAboutTitle = "Sobre o Android Tweaker",
            appInfoAboutBody = "Execute comandos ADB diretamente no seu dispositivo sem precisar de um computador."
        )

        AppLanguage.RUSSIAN -> Strings(
            navAdbConnection = "Adb подключение",
            navTweaks = "Твики",
            navAdbConsole = "Консоль ADB",
            navLanguage = "Язык",
            navInfo = "Инфо",
            navLicenses = "Лицензии Open Source",
            navRateUs = "Оцените нас в Play Store",
            disclaimerTitle = "Отказ от ответственности",
            disclaimerBody = "ВАЖНЫЙ ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ:\n\nЭто приложение выполняет команды ADB напрямую. Использование на ваш страх и риск.",
            disclaimerAccept = "Я понимаю и принимаю все риски",
            statusTitle = "Статус подключения",
            statusConnected = "Подключено (127.0.0.1:%d)",
            statusConnecting = "Подключение к ADB...",
            statusDisconnected = "Отключено",
            guideTitle = "Как подключить без ПК (Android 11+)",
            guideSteps = "1. Включите 'Параметры разработчика'.\n2. Включите 'Отладка по Wi-Fi'.\n3. Нажмите 'Подключить устройство по коду'.\n4. Введите порт и код!",
            pairHeader = "1. Сопряжение по Wi-Fi",
            pairPortLabel = "Порт сопряжения",
            pairCodeLabel = "Код сопряжения",
            pairButton = "Сопрячь устройство",
            connectHeader = "2. Подключение ADB",
            adbPortLabel = "Порт ADB",
            connectButton = "Подключить ADB",
            disconnectButton = "Отключить",
            dangerStepOneTitle = "Вы уверены, что хотите выполнить эту команду?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "Высокорисковое действие. Нажмите 'Продолжить' после завершения таймера.",
            dangerCancel = "Отмена",
            dangerProceed = "Продолжить",
            dangerProceedCountdown = "Продолжить (%d с)",
            dangerProceedReady = "ВЫПОЛНИТЬ СЕЙЧАС",
            catInfoTitle = "Информация",
            catInfoDesc = "Диагностика системы только для чтения",
            catAppControlTitle = "Управление приложениями",
            catAppControlDesc = "Управление пакетами и разрешениями",
            catSettingsTitle = "Настройки",
            catSettingsDesc = "Настройка интерфейса и поведения",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "Опасные опции - Риск сбоя системы",
            runCommand = "ВЫПОЛНИТЬ",
            dangerExecute = "ОПАСНОСТЬ ВЫПОЛНИТЬ",
            close = "Закрыть",
            selectLanguage = "Выберите язык приложения",
            appInfoAboutTitle = "О программе Android Tweaker",
            appInfoAboutBody = "Выполняйте команды ADB прямо на устройстве без использования компьютера."
        )

        AppLanguage.HINDI -> Strings(
            navAdbConnection = "Adb कनेक्शन",
            navTweaks = "ट्विक्स",
            navAdbConsole = "ADB कंसोल",
            navLanguage = "भाषा",
            navInfo = "जानकारी",
            navLicenses = "ओपनसोर्स लाइसेंस",
            navRateUs = "प्ले स्टोर पर हमें रेट करें",
            disclaimerTitle = "अस्वीकरण और शर्तें",
            disclaimerBody = "महत्वपूर्ण अस्वीकरण:\n\nयह ऐप सीधे ADB कमांड निष्पादित करता है। इसका उपयोग आपके अपने जोखिम पर है।",
            disclaimerAccept = "मैं सभी जोखिमों को समझता हूं और स्वीकार करता हूं",
            statusTitle = "कनेक्शन स्थिति",
            statusConnected = "कनेक्टेड (127.0.0.1:%d)",
            statusConnecting = "ADB से कनेक्ट हो रहा है...",
            statusDisconnected = "डिस्कनेक्ट किया गया",
            guideTitle = "बिना पीसी के कैसे कनेक्ट करें (Android 11+)",
            guideSteps = "1. डेवलपर विकल्प चालू करें।\n2. वायरलेस डिबगिंग चालू करें।\n3. पेयरिंग कोड के साथ डिवाइस पेयर करें।\n4. पोर्ट और कोड दर्ज करें!",
            pairHeader = "1. वायरलेस पेयरिंग",
            pairPortLabel = "पेयरिंग पोर्ट",
            pairCodeLabel = "पेयरिंग कोड",
            pairButton = "डिवाइस पेयर करें",
            connectHeader = "2. ADB कनेक्शन",
            adbPortLabel = "ADB पोर्ट",
            connectButton = "ADB कनेक्ट करें",
            disconnectButton = "डिस्कनेक्ट करें",
            dangerStepOneTitle = "क्या आप निश्चित रूप से यह कमांड चलाना चाहते हैं?",
            dangerStepTwoTitle = "LAST WARNING THE AUTHOR OF THE APP DOESN'T HAVE ANY RESPONSIBILITY!",
            dangerStepTwoSubtitle = "यह उच्च जोखिम वाली कार्रवाई है। टाइमर अनलॉक होने पर आगे बढ़ें।",
            dangerCancel = "रद्द करें",
            dangerProceed = "आगे बढ़ें",
            dangerProceedCountdown = "आगे बढ़ें (%d s)",
            dangerProceedReady = "अभी निष्पादित करें",
            catInfoTitle = "जानकारी",
            catInfoDesc = "सिस्टम निदान",
            catAppControlTitle = "ऐप नियंत्रण",
            catAppControlDesc = "पैकेज प्रबंधन और अनुमतियां",
            catSettingsTitle = "सेटिंग्स",
            catSettingsDesc = "UI अनुकूलन",
            catDangerTitle = "Danger-Tweaks",
            catDangerDesc = "उन्नत विकल्प - बूटलूप जोखिम",
            runCommand = "कमांड चलाएं",
            dangerExecute = "खतरा निष्पादित करें",
            close = "बंद करें",
            selectLanguage = "ऐप भाषा चुनें",
            appInfoAboutTitle = "Android Tweaker के बारे में",
            appInfoAboutBody = "बिना कंप्यूटर के सीधे अपने डिवाइस पर ADB कमांड निष्पादित करें।"
        )
    }
}
